# cnbot configuration file example
#
# You can use is without any modifications to play with demo.sh script.
# You have only to export two environment variables:
# - T - your Telegram API token
# - U - your user id
# Read on for more details

# cnbot can drive several bots. You have to put all of them to "bots" section
bots:
  # keys are bot names that will be used internally and mentioned in logs and as $BOT_NAME variable value
  DemoBot:
    # API token
    #     ._________.
    # +---| WARNING |--------------------------------------------------------+
    # | It is not secure to use environment variables to store your secrets. |
    # | I use environment variables here just to make your first run easier. |
    # +----------------------------------------------------------------------+
    token: "${T}"
    # Script to serve requests
    # Relative paths evaluate with respect of configuration file directory
    script: "demo.sh"
    # White list of users
    # It is possible to specify black list as "disallowed_users" list
    # However, white list is a high priority. So you must remove "allowed_users" list to enable black list
    #     ._________.
    # +---| WARNING |--------------------------------------------------------+
    # | Be very careful with black lists. You have to keep in mind that you  |
    # | allow almost everyone to run script on your system. Please consider  |
    # | running the bot with limited permissions.                            |
    # +----------------------------------------------------------------------+
    # You can use numbers in "disallowed_users":
    #   disallowed_users: [1538126281]
    # You can also use strings and environment variables in "allowed_users",
    # however it is convenient for tests and demos only,
    # in real life you will likely use just numbers:
    #   allowed_users: [1538126281]
    allowed_users: ["${U}"]
    # Script working directory
    # You may want to sent something like /tmp in respect of security
    # Relative paths evaluate with respect of configuration file directory
    # Default is the configuration file directory
    working_dir: "."
    # Maximum waiting time before sending SIGTERM to script
    # Default is 10
    term_timeout: 20
    # Gap in between SIGTERM and SIGKILL
    # Default is 1
    kill_timeout: 1
    # Time to wait process status after SIGKILL
    # Default is 1
    wait_timeout: 1
    # HTTP server to accept asynchronous message
    bind_address: "127.0.0.1:9091"
    # HTTP server's read/write timeouts
    # Default 10 for both
    read_timeout: 5
    write_timeout: 5
# Optional alive-handler address
# You can remove this section to disable alive-handler
alive:
  bind_address: "127.0.0.1:9999"
