[main]
  command = "./slave-script.sh"
  concurrent = 2
  cwd = "examples"
  env_force = ["LANG=C"]
  env_pass = ["HOME","PATH"]
  polling_interval = 50
  port = 9999
  timeout = 10
  token = "226015286:AAHzO9VmmKi-_uwZkmbA0DVn03DOpdYYsg4"
  whitelist = [153812628]
